---
- name: configure database
  include_role:
    name: vexxhost.openstack-oslo
    tasks_from: db
  vars:
    openstack_oslo_db_manage: "{{ openstack_keystone_manage_database }}"
    openstack_oslo_db_driver: "{{ openstack_keystone_database_driver }}"
    openstack_oslo_db_name: "{{ openstack_keystone_database_name }}"
    openstack_oslo_db_username: "{{ openstack_keystone_database_username }}"
    openstack_oslo_db_password: "{{ openstack_keystone_database_password }}"
    openstack_oslo_db_config_files:
      - "{{ __openstack_keystone_config_file }}"

- name: sync keystone database
  command: "{{ __openstack_keystone_manage_path }} db_sync"
  when: openstack_oslo_db_config_result.changed

- name: bootstrap keystone database
  command: "{{ __openstack_keystone_manage_path }} bootstrap"
  environment:
    OS_BOOTSTRAP_PROJECT_NAME: "{{ openstack_keystone_admin_project }}"
    OS_BOOTSTRAP_USERNAME: "{{ openstack_keystone_admin_username }}"
    OS_BOOTSTRAP_PASSWORD: "{{ openstack_keystone_admin_password }}"
    OS_BOOTSTRAP_PUBLIC_URL: http://localhost:5000
    OS_BOOTSTRAP_INTERNAL_URL: http://localhost:5000
    OS_BOOTSTRAP_ADMIN_URL: http://localhost:35357
  when: openstack_oslo_db_config_result.changed
...
